drop table BOOK_TBL if exists;

drop table USER_TBL if exists;

create table if not exists BOOK_TBL (
    ID integer generated by default as identity,
    TITLE varchar(40),
    AUTHOR_ID integer,
    primary key (ID)
);

create table USER_TBL (
    ID integer generated by default as identity,
    NAME varchar(20),
    PASSWORD varchar(80),
    ROLE char(5),
    primary key (ID)
);

alter table BOOK_TBL add constraint UK_BOOK_NAME unique (TITLE, AUTHOR_ID);

alter table USER_TBL add constraint UK_USER_NAME unique (NAME);

alter table BOOK_TBL
    add constraint FK_USER_ID 
    foreign key (AUTHOR_ID)
    references USER_TBL
    on delete cascade;

insert into USER_TBL values (1, 'admin', 'df0d1aaaef34e5456bf47aad5b6e72f693ac3f55670d30bb17637a932616f4c180979c630b6bc059', 'ADMIN');
